### ISSUE TITLE
Vuex in "Vue 3 as the New Default" announcement

### ISSUE THREAD

**Issue by jkosir** [vuejs/blog#7]
While the announcement suggest using Pinia as a global state management lib for Vue 3, it still also makes Vuex seem as a viable alternative. 
However in Vuex 4 getters caching does not work, as mentioned in Vuex documentation: https://next.vuex.vuejs.org/guide/getters.html
and on many issues in the vuex repository:
https://github.com/vuejs/vuex/pull/1883
https://github.com/vuejs/vuex/issues/2102

Neither the Vuex mentions or "Potential required actions" mention this even though it can be a complete blocker for migrating some apps to Vue 3 (without also changing the state management to Pinia). Can a warning be added (or said issue in Vuex fixed)?

**Comment by yyx990803** [comment]
This is now fixed in Vuex 4.1 (which requires Vue 3.2+)
